sudo: required
services:
  - docker

before_install:
  - docker build -t nikhilnvj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nikhilnvj/react-test npm test -- --coverage

after_success:
  - docker build -t nikhilnvj/multi-client ./client
  - docker build -t nikhilnvj/multi-server ./server
  - docker build -t nikhilnvj/multi-worker ./worker
  - docker build -t nikhilnvj/multi-nginx ./nginx
# Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Push to docker hub
  - docker push nikhilnvj/multi-client
  - docker push nikhilnvj/multi-server
  - docker push nikhilnvj/multi-worker
  - docker push nikhilnvj/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-477864128193
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY